server:
  port: 9775

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  sql:
    init:
      schema-locations: classpath:db/quartz_tables_h2.sql

  h2:
    console.enabled: true

  cloud:
    azure:
      storage:
        blob:
          account-name: absitdsdevwusseddw001
          account-key: yYF0293O1dHvHwfwKektJa3ptAMgH219Pp7886kyqQ/1EHivjCL4L9Dy+W/mx1JyjM+BEVqHC3xvSKkzKrbz7g==
          endpoint: https://absitdsdevwusseddw001.blob.core.windows.net

workspace:
  home: D:/github/Workshop/AppBuild

soya:
  framework:
    home: D:/github/Workshop
    scanPackages: soya.framework
    debug: true

  ant:
    home: ${soya.framework.home}/Ant

  git:
    home: D:/github/jgit

