server:
  port: 7833

spring.quartz.properties:
  org.quartz.threadPool.threadCount: 15

soya.framework.dovetails:
  server:
    home: D:/dovetails
    configuration: D:/dovetails/conf/server.properties