server:
  port: 7833

spring.quartz.properties:
  org.quartz.threadPool.threadCount: 15

soya.framework.dovetails.application:
  repository.home: D:/dovetails
  heartbeat.scan: 60
  heartbeat.keygen: 0 0/5 * * * ?