server:
  port: 7878

workspace:
  home: C:/github/Workshop/AppBuild

soya:
  framework:
    home: C:/github/Workshop
    scanPackages: soya.application.albertsons, soya.framework.commands.apache.kafka
    debug: true